output$mainui <- renderUI({
    mainPanel(
        h3("C-Plan software download"),
        br(),
        conditionalPanel(condition = "input.showform == '1'",
            HTML("To download this free software, please fill in your details and agree to the conditions set out below."),
            br(),
            conditionalPanel(condition = "input.showhint == '1'",
                br(),
                HTML(paste0("", tags$span(style="color:red", "Enter name, organisation, email")))
            ),
            textInput("name","Your name:"),
            textInput("organisation","Your organisation:"),
            selectInput("country","Your country:",choices=countrycode_data$country.name,selected="Australia"),
            textInput("email","Your email address:"),
            HTML("<a href='http://marxan.net/emaillist' target='_blank'>Subscribe to the Marxan mailing list</a>"),
            #checkboxInput("registerio","Register for the marxan.io web app?",value=FALSE),
            conditionalPanel(condition = "input.showregisterio == '1'",
                HTML("A password reset email will be sent to you. The password reset link will expire in 12 hours."),
                br(),
                br()
            ),
            selectInput("industry","Your industry:",choices=industry_list),
            selectInput("researchinterest","Your research interest:",choices=research_interest_list),
            conditionalPanel(condition = "input.showagree == '1'",
                br(),
                HTML(paste0("", tags$span(style="color:red", "You need to agree")))
            ),            
            HTML("By clicking the submit button you agree to the following terms and conditions:"),
            checkboxInput("informauthors",
                HTML(paste0("I agree to inform the authors ",
                    "<a href='mailto:mattejwatts@gmail.com?subject=Inform C-Plan Authors'>Matt Watts</span></a> and ",
                    "<a href='mailto:bob.pressey@jcu.edu.au?subject=Inform C-Plan Authors'>Bob Pressey</a>",
                    " of any publications, applications for funding, funding acquired and all other applications associated with this software")),
                value=FALSE,width=generate_screen_width()
            ),
            checkboxInput("acknowledgeip",
                HTML(paste0("I agree to ",
                    "<a href='http://marxan.net/citecplan' target='_blank'>acknowledge the intellectual property</a>",
                    " of the authors in all published work, applications and dealings with this software")),
                value=FALSE,width=generate_screen_width()
            ),
            br(),
            HTML("I agree:"),
            actionButton('submitUser', 'Submit'),
            br()
        ),
        conditionalPanel(condition = "input.showok == '1'",
            br(),
            h4("Download C-Plan"),

            HTML("<img src='http://marxan.net/downloads/cplan/CPLAN.BMP' alt='C-Plan Logo' />"),
            br(),
            h4("Download C-Plan Version 4.02 (1 file)"),
            HTML("<a href='http://marxan.net/downloads/cplan/CPlan402.exe'>C-Plan version 4.02</a>"),
            br(),
            HTML("Version 4.02 install set is compatible with Windows 7 64 bit. It is otherwise equivalent in functionality to version 4 and is compatiable with the <a href='http://marxan.net/zonaecogito' target='_blank'>Zonae Cogito decision support system</a> which serves as a GIS."),
            br(),
            h4("Download C-Plan Version 4 (1 file)"),
            HTML("<a href='http://marxan.net/downloads/cplan/CPlan4.zip'>C-Plan version 4</a>"),
            br(),
            HTML("Version 4 is compatiable with the <a href='http://marxan.net/zonaecogito' target='_blank'>Zonae Cogito decision support system</a> which serves as a GIS."),
            br(),
            h4("Download C-Plan Version 3.4 (4 files)"),
            HTML("<a href='http://marxan.net/downloads/cplan/CPlan_BDE_Install_DISK1.zip'>Database Engine install disk 1 of 2</a>"),
            br(),
            HTML("<a href='http://marxan.net/downloads/cplan/CPlan_BDE_Install_DISK2.zip'>Database Engine install disk 2 of 2</a>"),
            br(),
            HTML("<a href='http://marxan.net/downloads/cplan/CPLAN3.4.zip'>C-Plan version 3.4</a>"),
            br(),
            HTML("<a href='http://marxan.net/downloads/cplan/CPLAN_AVX.zip'>C-Plan ArcView extension</a>"),
            br(),
            HTML("Version 3.4 is compatiable with the ESRI ArcView 3.X GIS."),
            br(),
            br(),
            br(),
            actionButton('registerAnotherUser', 'Register another user'),
            br(),
            br(),
            tableOutput("registertable"),
            br()
        )
  )
})
